name: WakaTime status update

on:
 push:
    branches: [main]
 schedule:
    # Runs at 12 am  '0 0 * * *'  UTC
    - cron: "1 0 * * *" 

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
    steps:  
      - uses: LieBieS/LieBieS/.github/workflows@main
        env:
          # WakaTime API key stored in secrets, do not directly paste it here
          WAKATIME_API_KEY: ${{ env.WAKATIME_API_KEY }}
